# Generated by Django 5.1.4 on 2024-12-21 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_blogpost_employee_event_order_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subject', models.CharField(max_length=100)),
                ('hire_date', models.DateField()),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('experience', models.PositiveIntegerField(help_text='Enter experience in years')),
                ('salary', models.DecimalField(decimal_places=2, help_text='Enter salary in USD', max_digits=10)),
            ],
        ),
    ]
